### ISSUE TITLE
Maximum upload size exceeded

### ISSUE THREAD

**Issue by anikaliu** [qingshanni/TIPS#1]
Hello,
I'd like to give the pipeline a try but am not able to upload my data as the maximum upload size is exceeded. I'm happy to run it through our local server, but don't know how to adjust the code so this is feasible. Could you help me with this?

Best wishes,
Anika

**Comment by qingshanni** [comment]
You can modify the `shiny.maxRequestSize` option in file “global.R”. For example, `options(shiny.maxRequestSize=200*1024^2)` would increase the limit to 200M

**Comment by anikaliu** [comment]
Thank you!
